dependencies:
  environment: python
  libraries:
  - pandas
  - numpy
  - SciPy
  - opencv-python
  - PIL
  - shutil
  - glob
  - random
  - requests
  - kaggle
  - Pillow
  - matplotlib
  - scikit-learn
  - tensorflow
  python_version: '3.10'

